import { createAdapterBindings } from '../../adapterBindings.js';

export default function install(registry, context = {}) {
  const {
    SKILLS,
    _ARTISAN_TOOLS,
    _MUSICAL_INSTRUMENTS,
    _GAMING_SETS,
    _VEHICLE_TOOLS,
    _STD_LANGS,
    _EXOTIC_LANGS,
    _ALL_LANGS,
    _ALL_TOOLS,
    allItemsDb,
    registerClassAdapter,
    getClassAdapter,
    registerSubclassAdapter,
    getSubclassAdapter,
    registerSpeciesAdapter,
    getSpeciesAdapter,
    registerFeatAdapter,
    getFeatAdapter,
    registerClassSheetActions,
    getClassSheetActions,
    registerSubclassSheetActions,
    getSubclassSheetActions,
    registerSpeciesSheetActions,
    getSpeciesSheetActions,
    registerFeatSheetActions,
    getFeatSheetActions,
    registerClassSheetResources,
    getClassSheetResources,
    registerSubclassSheetResources,
    getSubclassSheetResources,
    registerSpeciesSheetResources,
    getSpeciesSheetResources,
    registerFeatSheetResources,
    getFeatSheetResources,
    registerClassSheetEffects,
    getClassSheetEffects,
    registerSubclassSheetEffects,
    getSubclassSheetEffects,
    registerSpeciesSheetEffects,
    getSpeciesSheetEffects,
    registerFeatSheetEffects,
    getFeatSheetEffects,
    registerClassRuntimeConfig,
    getClassRuntimeConfig,
    registerSubclassRuntimeConfig,
    getSubclassRuntimeConfig,
    registerSpeciesRuntimeConfig,
    getSpeciesRuntimeConfig,
    registerClassSheetChoiceMeta,
    getClassSheetChoiceMeta,
    registerSubclassSheetChoiceMeta,
    getSubclassSheetChoiceMeta,
    registerSpeciesSheetChoiceMeta,
    getSpeciesSheetChoiceMeta,
    registerClassSheetCommonChoiceMeta,
    registerSubclassSheetCommonChoiceMeta,
    registerSpeciesSheetCommonChoiceMeta,
    registerItemFlagDef,
    getItemFlagDef,
    getAllItemFlagDefs,
    registerWeaponAbilityOverride,
    getWeaponAbilityOverrides,
    registerClassSheetFeatureFilter,
    getClassSheetFeatureFilters,
    registerSubclassSheetFeatureFilter,
    getSubclassSheetFeatureFilters,
    registerSpeciesSheetFeatureFilter,
    getSpeciesSheetFeatureFilters,
    registerClassSheetProficiencies,
    getClassSheetProficiencies,
    registerSubclassSheetProficiencies,
    getSubclassSheetProficiencies,
    registerSpeciesSheetProficiencies,
    getSpeciesSheetProficiencies,
    registerClassSheetSpellModifiers,
    getClassSheetSpellModifiers,
    registerSubclassSheetSpellModifiers,
    getSubclassSheetSpellModifiers,
    registerSpeciesSheetSpellModifiers,
    getSpeciesSheetSpellModifiers,
    registerClassChoiceKeyFilter,
    getClassChoiceKeyFilter,
    registerClassChoiceLabelProvider,
    getClassChoiceLabelProvider,
    registerSpeciesSheetHpBonus,
    getSpeciesSheetHpBonus,
    registerClassAtWillSpells,
    getClassAtWillSpells,
    registerSpeciesLongRestGrants,
    getSpeciesLongRestGrants,
    registerResourceSideEffect,
    getResourceSideEffect,
    registerSubclassChoiceDetailDataProvider,
    getSubclassChoiceDetailDataProvider,
    registerGlobalClassAdapter,
    getGlobalClassAdapters,
    registerGlobalSubclassAdapter,
    getGlobalSubclassAdapters,
    registerGlobalSpeciesAdapter,
    getGlobalSpeciesAdapters,
    registerGlobalFeatAdapter,
    getGlobalFeatAdapters,
    registerGlobalSpellAdapter,
    getGlobalSpellAdapters,
    registerGlobalItemAdapter,
    getGlobalItemAdapters,
    registerCantripData,
    getCantripData,
    registerCantripDataModifier,
    getCantripDataModifiers,
    registerSpellData,
    getSpellData,
    getGenericSpeciesChoiceSpecs,
    getGenericBackgroundChoiceSpecs,
    getGenericBackgroundChoiceMeta,
    getGenericBackgroundOriginFeat,
  } = createAdapterBindings(registry, context);
registerSubclassAdapter("Bard_Moon", function (cls, lv, specs) {
  if (lv >= 3) {
    specs.push({
      key: "subclass_moon_primal_lore_skill",
      label: "Primal Lore Skill (Moon)",
      type: "skill_choice",
      from: ["Animal Handling", "Insight", "Medicine", "Nature", "Perception", "Survival"],
      count: 1,
      level: 3,
    });
    specs.push({
      key: "subclass_moon_primal_lore_cantrip",
      label: "Primal Lore Cantrip (Moon)",
      type: "spell_choice",
      spellFilter: { spellLevel: 0, classes: ["Druid"] },
      count: 1,
      level: 3,
    });
  }
});

// [SheetRuntime] START
registerSubclassSheetActions("Bard_Moon", [
  { name: "Moon's Inspiration", icon: "", cat: "bonus",    uses: "With Bardic Insp.", minLevel: 3,
    desc: "Inspired Eclipse: when you take a Bonus Action to give a creature Bardic Inspiration, you can also become Invisible and teleport up to 30 ft to an unoccupied space you can see. Invisible until start of your next turn (ends early after attack roll, dealing damage, or casting a spell). Lunar Vitality: once per turn when you restore HP to a creature with a spell, you can expend a Bardic Inspiration die and add the die's result to the HP restored; the creature's Speed also increases by 10 ft until end of its next turn." },
  { name: "Primal Lore",        icon: "", cat: "action",   uses: "Passive",           minLevel: 3,
    desc: "You learn Druidic, gain one Druid cantrip (counts as Bard spell; swappable on level-up), and gain proficiency in one of: Animal Handling, Insight, Medicine, Nature, Perception, or Survival." },
  { name: "Blessing of Moonlight", icon: "", cat: "action", uses: "1 / LR", resKey: "moon_blessing", minLevel: 6,
    desc: "Moonbeam is always prepared. Once per Long Rest when you cast Moonbeam, you can modify it: you shed Dim Light in a 5-ft radius while the spell is active, and whenever a creature fails its saving throw against this Moonbeam, another creature of your choice within 60 ft regains 2d4 HP." },
  { name: "Eventide's Splendor", icon: "", cat: "action", uses: "Passive", minLevel: 14,
    desc: "Shadow of the New Moon: when you use Inspired Eclipse, the creature who received Bardic Inspiration can also become Invisible and immediately use a Reaction to teleport up to 30 ft to an unoccupied space it can see (Invisible until start of its next turn). Vibrance of the Full Moon: when you use Lunar Vitality, you can roll 1d6 and use that result instead of expending a Bardic Inspiration die." },
]);

registerSubclassSheetResources("Bard_Moon", [
  { key: "moon_blessing", name: "Blessing of Moonlight", icon: "moon", recharge: "LR", actionName: "Blessing of Moonlight", max: (lv) => lv >= 6 ? 1 : 0 },
]);

registerSubclassSheetProficiencies("Bard_Moon", [
  { type: "language", values: ["Druidic"], minLevel: 3 },
]);
// [SheetRuntime] END

}

